// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	types "Go-Dispatch-Bootcamp/types"

	mock "github.com/stretchr/testify/mock"
)

// DemoService is an autogenerated mock type for the DemoService type
type DemoService struct {
	mock.Mock
}

// FetchCsvFromRemote provides a mock function with given fields:
func (_m *DemoService) FetchCsvFromRemote() ([][]string, error) {
	ret := _m.Called()

	var r0 [][]string
	if rf, ok := ret.Get(0).(func() [][]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFeedUsers provides a mock function with given fields:
func (_m *DemoService) GetFeedUsers() ([][]string, error) {
	ret := _m.Called()

	var r0 [][]string
	if rf, ok := ret.Get(0).(func() [][]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsers provides a mock function with given fields:
func (_m *DemoService) GetUsers() (*[]types.User, error) {
	ret := _m.Called()

	var r0 *[]types.User
	if rf, ok := ret.Get(0).(func() *[]types.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]types.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsersMap provides a mock function with given fields:
func (_m *DemoService) GetUsersMap() (map[int]types.User, error) {
	ret := _m.Called()

	var r0 map[int]types.User
	if rf, ok := ret.Get(0).(func() map[int]types.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int]types.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUsers provides a mock function with given fields: _a0
func (_m *DemoService) UpdateUsers(_a0 *[]types.User) (bool, error) {
	ret := _m.Called(_a0)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*[]types.User) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*[]types.User) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
