// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// demoController is an autogenerated mock type for the demoController type
type DemoController struct {
	mock.Mock
}

// Feed provides a mock function with given fields: w, r
func (_m *DemoController) Feed(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// Fetch provides a mock function with given fields: w, r
func (_m *DemoController) Fetch(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// FetchById provides a mock function with given fields: w, r
func (_m *DemoController) FetchById(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// UpdateUsersFromFeed provides a mock function with given fields: w, r
func (_m *DemoController) UpdateUsersFromFeed(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}
